[workspace]
resolver = "2"
members = ["crates/zoll", "crates/editor", "crates/api", "crates/gui"]

[package]
name = "Zol"
version = "0.3.6"
edition = "2024"

[dependencies]
gui = { path = "crates/gui" }
iced = "0.14.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
